name: QA

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build, lint, unit tests
        uses: actions/setup-node@v3
        run: |
          yarn
          yarn qa
